swagger: '2.0'

info:
  version: "0.0.1"
  title: service-hml-fhir-converter-api
  description: Hml and Fhir conversion service

schemes:
  - https

produces:
  - application/json

paths:
  /hml:
    post:
      operationId: convert
      parameters:
        -
          in: body
          name: hmls
          required: true
          schema:
            items:
              $ref: '#/definitions/Hml'
            type: array
      responses:
        200:
          schema:
            type: boolean
        500:
          schema:
            $ref: '#/definitions/Error'
          title: ErrorException
  /fhir:
    post:
      operationId: convert
      parameters:
        -
          in: body
          name: fhirMessages
          required: true
          schema:
            items:
              $ref: '#/definitions/FhirMessage'
            type: array
      responses:
        200:
          schema:
            type: boolean
        500:
          schema:
            $ref: '#/definitions/Error'
          title: ErrorException
definitions:
  Hml:
    properties:
      id:
        type: string
    type: object
  FhirMessage:
    allOf:
    - $ref: '#/definitions/Message'
    - type: object
      properties:
        id:
          type: string
  Message:
    properties:
      name:
        type: string
    type: object
  Error:
    properties:
      id:
        type: string
    type: object